eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# spring:
#   cloud:
#     gateway:
#       routes:
#       - id: book_instance_route
#         uri: lb://CATALOGUE_SERVICE
#         predicates:
#         - Path=/api/book-instances/**